### ISSUE TITLE
org.openjavacard.smartcardio.android.demo crashed in NfcCardTerminal.connect

### ISSUE THREAD

**Issue by rena2019** [OpenJavaCard/openjavacard-smartcardio#4]
I just tried the demo app on my Pixel 3 with Android 10. There's my locat:

2020-07-15 16:05:47.290 9845-9845/org.openjavacard.smartcardio.android.demo D/org.openjavacard.smartcardio.android.demo.activity.MainActivity: switchToTerminalInfo(org.openjavacard.smartcardio.android.nfc.NfcCardTerminal@afdfdb9)
2020-07-15 16:05:48.569 9845-9845/org.openjavacard.smartcardio.android.demo D/org.openjavacard.smartcardio.android.demo.activity.MainActivity: updateWakeTimer()
2020-07-15 16:05:53.081 9845-9845/org.openjavacard.smartcardio.android.demo D/org.openjavacard.smartcardio.android.nfc.NfcCardTerminal: connect(*)
2020-07-15 16:05:53.083 9845-9845/org.openjavacard.smartcardio.android.demo W/io.android.dem: Got a deoptimization request on un-deoptimizable method void android.os.MessageQueue.nativePollOnce(long, int)
2020-07-15 16:05:53.083 9845-9845/org.openjavacard.smartcardio.android.demo E/InputEventReceiver: Exception dispatching input event.
2020-07-15 16:05:53.084 9845-9845/org.openjavacard.smartcardio.android.demo E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2020-07-15 16:05:53.084 1372-1677/? I/InputDispatcher: Window 'f7341d5 org.openjavacard.smartcardio.android.demo/org.openjavacard.smartcardio.android.demo.activity.MainActivity (server)' spent 13919.2ms processing the last input event: MotionEvent
2020-07-15 16:05:53.143 9845-9845/org.openjavacard.smartcardio.android.demo E/MessageQueue-JNI: java.lang.IllegalStateException: Close other technology first!
        at android.nfc.Tag.setConnectedTechnology(Tag.java:462)
        at android.nfc.tech.BasicTagTechnology.connect(BasicTagTechnology.java:78)
        at android.nfc.tech.IsoDep.connect(IsoDep.java:40)
        at org.openjavacard.smartcardio.android.nfc.NfcCardTerminal.connect(NfcCardTerminal.java:54)
        at org.openjavacard.smartcardio.android.demo.fragment.TerminalInfoFragment.setTerminal(TerminalInfoFragment.java:87)
        at org.openjavacard.smartcardio.android.demo.activity.MainActivity.switchToTerminalInfo(MainActivity.java:229)
        at org.openjavacard.smartcardio.android.demo.fragment.TerminalListFragment.onListItemClick(TerminalListFragment.java:59)
        at android.support.v4.app.ListFragment$2.onItemClick(ListFragment.java:63)
        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:4128)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3886)
        at android.view.View.dispatchTouchEvent(View.java:13953)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4012)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
        at android.view.View.dispatchPointerEvent(View.java:14212)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5652)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5455)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
    	at android.vi
2020-07-15 16:05:53.143 9845-9845/org.openjavacard.smartcardio.android.demo W/io.android.dem: Got a deoptimization request on un-deoptimizable method void android.os.MessageQueue.nativePollOnce(long, int)
2020-07-15 16:05:53.143 9845-9845/org.openjavacard.smartcardio.android.demo W/io.android.dem: Got a deoptimization request on un-deoptimizable method java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])
2020-07-15 16:05:53.143 9845-9845/org.openjavacard.smartcardio.android.demo W/io.android.dem: Got a deoptimization request on un-deoptimizable method java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])

**Comment by promovicz** [comment]
Thanks for the trace. Will take a look at some point once I get to finishing this library.
